googleapis/python-pubsublite

.gitignore, google/cloud/pubsublite/internal/wire/make_publisher.py, google/cloud/pubsublite/internal/wire/partition_count_watcher.py, google/cloud/pubsublite/internal/wire/partition_count_watcher_impl.py, google/cloud/pubsublite/internal/wire/partition_count_watching_publisher.py, google/cloud/pubsublite/testing/test_utils.py, tests/unit/pubsublite/internal/wire/partition_count_watcher_impl_test.py, tests/unit/pubsublite/internal/wire/partition_count_watching_publisher_test.py
Fixes #<issue_number_goes_here> 🦕
=> feat: Add support for increasing partitions in python

google/cloud/pubsublite/cloudpubsub/internal/single_publisher.py, google/cloud/pubsublite/cloudpubsub/message_transforms.py, google/cloud/pubsublite/cloudpubsub/publisher_client_interface.py, google/cloud/pubsublite/internal/wire/partition_count_watching_publisher.py, google/cloud/pubsublite/internal/wire/publisher.py, google/cloud/pubsublite/internal/wire/routing_publisher.py, google/cloud/pubsublite/internal/wire/single_partition_publisher.py, google/cloud/pubsublite/types/__init__.py, google/cloud/pubsublite/types/message_metadata.py, noxfile.py, samples/snippets/publish_with_batch_settings_example.py, samples/snippets/publish_with_custom_attributes_example.py, samples/snippets/publish_with_ordering_key_example.py, samples/snippets/publisher_example.py, samples/snippets/subscriber_example.py, tests/unit/pubsublite/cloudpubsub/message_transforms_test.py
=> fix: Rename PublishMetadata to MessageMetadata

google/cloud/pubsublite/internal/wire/assigner_impl.py, google/cloud/pubsublite/internal/wire/committer_impl.py, google/cloud/pubsublite/internal/wire/pubsub_context.py, google/cloud/pubsublite/internal/wire/single_partition_publisher.py, setup.py, testing/constraints-3.6.txt
Use the standard python logging module instead.
=> fix: remove absl dependency

google/cloud/pubsublite/cloudpubsub/internal/multiplexed_publisher_client.py, google/cloud/pubsublite/cloudpubsub/internal/publisher_impl.py, google/cloud/pubsublite/cloudpubsub/publisher_client.py, google/cloud/pubsublite/cloudpubsub/publisher_client_interface.py
=> fix: Remove Future type hint from return type which fails to type check when overridden

google/cloud/pubsublite/cloudpubsub/internal/multiplexed_subscriber_client.py, google/cloud/pubsublite/cloudpubsub/subscriber_client.py, google/cloud/pubsublite/cloudpubsub/subscriber_client_interface.py
The overrides library doesn't like the Callable type and breaks.
https://github.com/mkorpela/overrides/issues/78
=> fix: Change type hint on callback to be Callback.

google/cloud/pubsublite/cloudpubsub/internal/multiplexed_publisher_client.py, google/cloud/pubsublite/cloudpubsub/internal/multiplexed_subscriber_client.py, google/cloud/pubsublite/cloudpubsub/internal/publisher_impl.py, google/cloud/pubsublite/cloudpubsub/publisher_client.py, google/cloud/pubsublite/cloudpubsub/publisher_client_interface.py, google/cloud/pubsublite/cloudpubsub/subscriber_client.py, google/cloud/pubsublite/cloudpubsub/subscriber_client_interface.py, setup.py
=> fix: Version bump overrides library past fix and undo workarounds

.github/CODEOWNERS
=> chore: add yoshi-python team to code owners

google/cloud/pubsublite/internal/wire/reset_signal.py, google/cloud/pubsublite/testing/test_reset_signal.py, tests/unit/pubsublite/internal/wire/reset_signal_test.py
When [trailing_metadata is None](https://github.com/grpc/grpc/blob/6730d93a3ac1f9bbfb6cef57fe12718779db352c/src/python/grpcio_status/grpc_status/rpc_status.py#L47), `rpc_status.from_call()` returns None. This needs to be handled when detecting the `RESET` signal.
=> fix: is_reset_signal should handle status that is None

google/cloud/pubsublite/cloudpubsub/internal/ack_set_tracker_impl.py, tests/unit/pubsublite/cloudpubsub/internal/ack_set_tracker_impl_test.py
Although all messages are received by the subscriber, there was always backlog and commits appeared to be delayed.
Fix: Since `_receipts.popleft()` is called, the receipt should be reinserted using `_receipts.appendleft()`.
=> fix: Backlog never zero despite messages received

google/cloud/pubsublite/cloudpubsub/internal/single_partition_subscriber.py, tests/unit/pubsublite/cloudpubsub/internal/single_partition_subscriber_test.py
Increment the ack generation id correctly. `++` does not increment in Python.
=> fix: Increment ack generation id

google/cloud/pubsublite/cloudpubsub/internal/client_multiplexer.py, google/cloud/pubsublite/cloudpubsub/internal/managed_event_loop.py, google/cloud/pubsublite/cloudpubsub/internal/multiplexed_async_publisher_client.py, google/cloud/pubsublite/cloudpubsub/internal/multiplexed_async_subscriber_client.py, google/cloud/pubsublite/cloudpubsub/internal/multiplexed_publisher_client.py, google/cloud/pubsublite/cloudpubsub/internal/multiplexed_subscriber_client.py, google/cloud/pubsublite/cloudpubsub/internal/publisher_impl.py, google/cloud/pubsublite/cloudpubsub/internal/subscriber_impl.py, google/cloud/pubsublite/internal/wire/committer_impl.py, google/cloud/pubsublite/internal/wire/serial_batcher.py, google/cloud/pubsublite/internal/wire/single_partition_publisher.py, google/cloud/pubsublite/types/paths.py, testing/constraints-3.6.txt, tests/unit/pubsublite/cloudpubsub/internal/async_client_multiplexer_test.py, tests/unit/pubsublite/cloudpubsub/internal/client_multiplexer_test.py
Fixes #<issue_number_goes_here> 🦕
=> fix: Numerous small performance and correctness issues

google/cloud/pubsublite/cloudpubsub/internal/managed_event_loop.py
Fixes #<issue_number_goes_here> 🦕
=> fix: Add workaround for https://github.com/grpc/grpc/issues/25364

google/cloud/pubsublite/cloudpubsub/internal/assigning_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/multiplexed_async_subscriber_client.py, google/cloud/pubsublite/cloudpubsub/internal/single_partition_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/single_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/subscriber_impl.py, google/cloud/pubsublite/cloudpubsub/message_transforms.py, google/cloud/pubsublite/internal/fast_serialize.py, google/cloud/pubsublite/internal/wire/flow_control_batcher.py, google/cloud/pubsublite/internal/wire/permanent_failable.py, google/cloud/pubsublite/internal/wire/subscriber.py, google/cloud/pubsublite/internal/wire/subscriber_impl.py, google/cloud/pubsublite/types/message_metadata.py, noxfile.py, samples/snippets/subscriber_example.py, tests/unit/pubsublite/cloudpubsub/internal/multiplexed_async_subscriber_client_test.py, tests/unit/pubsublite/cloudpubsub/internal/single_partition_subscriber_test.py, tests/unit/pubsublite/cloudpubsub/internal/subscriber_impl_test.py, tests/unit/pubsublite/cloudpubsub/message_transforms_test.py, tests/unit/pubsublite/internal/wire/subscriber_impl_test.py
The primary change here is to access the raw proto in as many places as possible due to proto-plus-python performance issues.
The secondary change is to reduce the asyncio overhead by propagating batches through more layers of code.
=> fix: performance issues with subscriber client

google/cloud/pubsublite/cloudpubsub/internal/ack_set_tracker.py, google/cloud/pubsublite/cloudpubsub/internal/ack_set_tracker_impl.py, google/cloud/pubsublite/cloudpubsub/internal/assigning_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/single_partition_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/subscriber_impl.py, google/cloud/pubsublite/internal/wire/committer.py, google/cloud/pubsublite/internal/wire/committer_impl.py, google/cloud/pubsublite/internal/wire/flow_control_batcher.py, google/cloud/pubsublite/internal/wire/subscriber.py, google/cloud/pubsublite/internal/wire/subscriber_impl.py, tests/unit/pubsublite/cloudpubsub/internal/ack_set_tracker_impl_test.py, tests/unit/pubsublite/cloudpubsub/internal/single_partition_subscriber_test.py, tests/unit/pubsublite/internal/wire/committer_impl_test.py, tests/unit/pubsublite/internal/wire/flow_control_batcher_test.py, tests/unit/pubsublite/internal/wire/subscriber_impl_test.py
also fix error propagation to streaming pull future
=> fix: ensure ack() doesn't wait on stream messages

google/cloud/pubsublite/cloudpubsub/internal/ack_set_tracker_impl.py, google/cloud/pubsublite/cloudpubsub/internal/single_partition_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/sorted_list.py, google/cloud/pubsublite/internal/wire/assigner_impl.py, google/cloud/pubsublite/internal/wire/committer_impl.py, google/cloud/pubsublite/internal/wire/connection_reinitializer.py, google/cloud/pubsublite/internal/wire/retrying_connection.py, google/cloud/pubsublite/internal/wire/single_partition_publisher.py, google/cloud/pubsublite/internal/wire/subscriber_impl.py, tests/unit/pubsublite/internal/wire/retrying_connection_test.py
There are two main retrying_connection race conditions fixed here:
1) Improper handling of cancelled write tasks can cause set_exception to be called when the task is already cancelled, which raises an InvalidStateError which is never caught by the existing code.
2) There is a race where if reinitialize() is called after queues are cycled, meaning a poller from the old instance of the class can add a message to the new queues. This has been fixed by splitting the ConnectionReinitializer interface into "stop_processing" and "reinitialize" parts.
Also fix other performance issues identified in profiles.
Something close to this code has been running for an hour or two on compute engine with no hangs.
=> fix: Race conditions and performance issues

google/cloud/pubsublite/cloudpubsub/internal/assigning_subscriber.py, google/cloud/pubsublite/cloudpubsub/internal/make_subscriber.py, google/cloud/pubsublite/cloudpubsub/nack_handler.py, google/cloud/pubsublite/cloudpubsub/publisher_client.py, google/cloud/pubsublite/cloudpubsub/reassignment_handler.py, google/cloud/pubsublite/cloudpubsub/subscriber_client.py, google/cloud/pubsublite/internal/wire/permanent_failable.py, tests/unit/pubsublite/cloudpubsub/internal/assigning_subscriber_test.py, tests/unit/pubsublite/cloudpubsub/internal/single_partition_subscriber_test.py
This enables clients to respond to a reassignment by cancelling outstanding actions and nacking all messages.
=> feat: Add ReassignmentHandler which is notified on client reassignment

.repo-metadata.json, README.rst
Updating the reference documentation website from googleapis.dev to cloud.google.com for the index pages. Also updating references in the README.
=> chore: update doc links from googleapis.dev to cloud.google.com

.github/sync-repo-settings.yaml
3.6 went end-of-life in December.
=> chore: make samples 3.6 check optional

samples/snippets/create_lite_reservation_example.py, samples/snippets/delete_lite_reservation_example.py, samples/snippets/get_lite_reservation_example.py, samples/snippets/list_lite_reservations_example.py, samples/snippets/quickstart_test.py, samples/snippets/update_lite_reservation_example.py
Towards b/213558019
Adding Python samples for the following region tags:
- `pubsublite_create_reservation`
- `pubsublite_get_reservation`
- `pubsublite_update_reservation`
- `pubsublite_list_reservations`
- `pubsublite_delete_reservation`
Java already added in https://github.com/googleapis/java-pubsublite/pull/1028
=> samples: add reservation samples

google/cloud/pubsublite/internal/wire/permanent_failable.py
=> fix: ensure that _failure_task exception is always retrieved

google/cloud/pubsublite/internal/wire/flow_control_batcher.py, tests/unit/pubsublite/internal/wire/flow_control_batcher_test.py
This can happen if the server sends a message that goes over the byte limit, which should never happen, but apparently does in edge cases. This ensures that the client doesn't fail if this happens.
fixes: #294
=> fix: ensure bytes cannot go negative on requests sent to the server

testing/constraints-3.7.txt
Test the minimum supported dependencies in python 3.7 unit tests to prepare for dropping python 3.6
=> chore: test minimum dependencies in python 3.7

google/cloud/pubsublite/__init__.py, google/cloud/pubsublite/admin_client.py, google/cloud/pubsublite/admin_client_interface.py, google/cloud/pubsublite/internal/wire/admin_client_impl.py
Support creating subscriptions at a nominated target location within the message backlog. A seek is performed for publish and event timestamps.
Export subscriptions (pre-release feature) are also supported.
=> feat: Create subscriptions at a seek target

google/cloud/pubsublite/cloudpubsub/internal/make_publisher.py, google/cloud/pubsublite/cloudpubsub/publisher_client.py, google/cloud/pubsublite/internal/publish_sequence_number.py, google/cloud/pubsublite/internal/publisher_client_id.py, google/cloud/pubsublite/internal/wire/make_publisher.py, google/cloud/pubsublite/internal/wire/single_partition_publisher.py, google/cloud/pubsublite/types/message_metadata.py, tests/unit/pubsublite/internal/wire/single_partition_publisher_test.py
Implements publish idempotence (default enabled), where the server will ensure that unique messages within a single publisher session are only stored once.
=> feat: Publish idempotence

google/cloud/pubsublite/cloudpubsub/publisher_client.py
The python library sends batches out of order, which fails validation on the server when publish idempotence is enabled.
=> fix: Disable publish idempotence by default
